### ISSUE TITLE
Add to cart option is visible for regions other than US as well

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#1259]
Hi @mhaack 
As discussed over slack add to cart option is visible for regions other than US as well for below page.
https://www.moleculardevices.com/products/culture-media-reagents/clonematrix#ordering-options
As instructed changed "Hero Advanced " class to 'Hero' with that it started appearing in header as well which is not required for such pages as design is being distorted.
![cart-ugly-deasign](https://github.com/hlxsites/moleculardevices/assets/42608830/133c8630-3022-4bbb-b015-409788054939)
For such page it'll be visible only in Ordering options . Please see https://live-md30.pantheonsite.io/products/culture-media-reagents/clonematrix#ordering-options for reference 

Regards,
Rajneesh

**Comment by mhaack** [comment]
Display rule for order options:
* Hero Banner > show order options in hero area
* Hero Advanced Banner > no order options in hero area

**Comment by mhaack** [comment]
When Hero Advance is used there is

```
failed to load module for ordering-options TypeError: Cannot read properties of null (reading 'querySelector')
    at showHideStoreFeature (ordering-options.js:421:31)
    at Module.decorate (ordering-options.js:462:3)
    at async lib-franklin.js:460:15
```

which breaks the show/hidde logic, hence all add2cart buttons are visible in all regions.

**Comment by dev-rajneeshkumar** [comment]
@mhaack  actually we were also looking into it. So if you are done then please confirm if you are going to merge it or we need to merge our changes ?
When we checked your url then by switching  on VPN add to cart is not visible instantly in same window , we have to  test it in other browser then it's working fine, same is the case with our fix.
